version: "3.8"
services:
  # Database Server
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    ports:
      - 25672:25672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: always
    volumes:
      - /dokcer_conf/rabbitmq/data/:/var/lib/rabbitmq
  database:
    #    image: mariadb
    #    ports:
    #      - 3306:3306
    #    environment:
    #      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    #    volumes:
    #      - "db-data:/var/lib/mariadb/"
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_USER: ${MSSQL_SA_USER}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
#    image: postgres:latest
#    container_name: postgres_container
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/
volumes:
  db-data: ~
  logs-folder:
    name: ${log_rabbitmq_management}
    driver: local